url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
iconURL: /assets/img/logo.png


## Default
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

# Where things are
#source              : .
#destination         : ./_site
#collections_dir     : .
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
  #collections:
  #posts:
  #  output          : true

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
#limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
#theme               : jekyll-theme-leaf
#remote_theme:  supun-io/jekyll-theme-leaf 
remote_theme: alainpham/alainpham.github.io
# Conversion
page_excerpts       : true
excerpt_separator   : "<!--more-->"
incremental         : false

# Serving
#detach              : false
#port                : 4000
#host                : 192.168.4.100
#baseurl             : "" # does not include hostname
#show_dir_listing    : false

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

